[package]
name = "more"
version = "2.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
varlink = { path = "../../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
getopts = "0"
chainerror = { version = "0.3", path = "../../../../chainerror"}

[build-dependencies]
varlink_generator = { path = "../../varlink_generator" }
