[package]
name = "varlink_generator"
version = "6.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"

license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink"
repository = "https://github.com/varlink/rust"
description = "Rust code generator for the varlink protocol."
readme = "README.md"

keywords = ["varlink", "ipc", "rpc", "protocol"]
categories = ["os", "development-tools", "network-programming"]

[lib]
name = "varlink_generator"
path = "src/lib.rs"

[[bin]]
name = "varlink-rust-generator"
path = "src/bin/varlink-rust-generator.rs"

[dependencies]
chainerror = { version = "0.3", path = "../../../chainerror"}
varlink_parser = { version = "2.1", path = "../varlink_parser" }
quote = "0.6"
proc-macro2 = "0.4"
getopts = "0"
syn = "0.15.0"

[badges]
travis-ci = { repository = "varlink/rust" }
coveralls = { repository = "varlink/rust", branch = "master", service = "github" }
